# Generated by Django 5.2.1 on 2025-05-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_author_tag_alter_post_date_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blog/img"),
        ),
    ]
