name: Generar documentació pydoc i fer tests

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instal·lar dependències
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install django

    - name: Generar documentació pydoc
      run: |
        python generate_docs.py

    - name: Pujar docs al repositori (commit)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add blog.models.html
        git add blog.tests.html
        git add blog.views.html
        git commit -m "Actualitzar documentació pydoc" || echo "No hi ha canvis per commitar"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Tests
      run: |
        python manage.py test
